brightbox/brightbox-cli

lib/brightbox-cli/gli_global_hooks.rb
I was having a problem developing a new authentication feature but
getting no useful error messages. I discovered we've got a blanket
silent rescue in the auth handling code. I've changed it so that if
DEBUG mode is enabled, the exception is printed out.
=> Report non-auth exceptions during auth in DEBUG mode

README, lib/brightbox-cli/config.rb, lib/brightbox-cli/config/authentication_tokens.rb, lib/brightbox-cli/config/gpg_encrypted_passwords.rb, lib/brightbox-cli/version.rb, lib/brightbox_cli.rb
When a password is needed for an account, check to see if it has been
gpg-encrypted and stored in a local file first, and attempt to decrypt
it with gpg.
It looks for ~/.brightbox/john@johnleach.co.uk.password.gpg and just
executes "gpg --decrypt" on it. The idea is that you'll combine it
with a gpg key daemon, such as GNOME's seahorse.
If the gpg binary isn't in the path, decryption will not be attempted
and you'll just be prompted for your password as usual.
You can encrypt a password by running this command:
gpg --encrypt --recipient john@brightbox.co.uk > ~/.brightbox/john@johnleach.co.uk.password.gpg
and then typing your password, followed by CTRL+D
Any carriage returns in the decrypted password are ignored. You can
"forget" the password by just removing that file.
=> Support encrypted stored passwords

lib/brightbox-cli/commands/servers/create.rb, tools/bash_completion_script
This selects the new 1GB SSD server type as the default when
no argument is provided by the client.
Also updates the autocompletion list of server handles recognised.
=> New SSD default and updated autocompletion

brightbox-cli.gemspec
brightbox-cli's gemspec has a dependency on mime-types "~> 1.25" even though it's not using it. It's causing problems when you have brightbox-cli in a project's Gemfile with other gems who depend on more recent versions of mime-types.
=> Remove dependency on mime-types gem

Gemfile.lock, brightbox-cli.gemspec
`net-ssh` 3.0 dropped 1.9.3 support. Attempting to install the CLI on
ruby 1.9.3 would fail as it pulled in the incompatible gem versions.
This limits the version (which is not directly used) to allow
installation to work.
=> Limit Net::SSH dependency for Ruby 1.9.3

lib/brightbox-cli/commands/config/client-list.rb, lib/brightbox-cli/config/clients.rb, lib/brightbox-cli/config/user_application.rb, lib/brightbox_cli.rb, spec/configs/user_app.ini, spec/unit/brightbox/bb_config/using_client_spec.rb, spec/unit/brightbox/config/user_application/to_fog_spec.rb, spec/unit/brightbox/config/user_application/valid_spec.rb
This adds a default user application set of credentials (which still
MUST be used with a username/password) which are used if the ID/secret
are not configured.
This will allow us to cut down the complexity of setting up new
configurations since only the email (username) and password (prompt)
will be needed.
=> [#105296840] Default to embedded app if not set

lib/brightbox-cli/config.rb, lib/brightbox-cli/config/accounts.rb, lib/brightbox-cli/config/clients.rb, lib/brightbox-cli/config/sections.rb, lib/brightbox-cli/gli_global_hooks.rb, spec/commands/accounts/list_spec.rb, spec/support/config_helpers.rb, spec/unit/brightbox/bb_config/account_spec.rb, spec/unit/brightbox/bb_config/client_name_spec.rb, spec/unit/brightbox/bb_config/config_directory_spec.rb, spec/unit/brightbox/bb_config/config_spec.rb, spec/unit/brightbox/bb_config/default_account_spec.rb, spec/unit/brightbox/bb_config/find_or_set_default_account_spec.rb, spec/unit/brightbox/bb_config/renew_tokens_spec.rb
The original implementation of `#client_name` and `#config` relied
on side-effects in the behaviour of the config.
Creating it was a lighter process, then referencing `#config` would
create directories, load the ini file. However it meant a number of
methods were equally complex because they had to call this
internally.
For `#selected_config` this also hit `#client_name` that performed
a few things and erred if config data was missing or ambiguous.
Trying to setup a new configuration section would then end up with
a series of problems when adding one would be impossible because
a later step referenced a full config.
The workaround used previously `force_default_config` appears to
be buggy in that it just skipped raising one error in one check but
the wrong client would be returned by …
=> Reduce complexity of `BBConfig#client_name`

Gemfile.lock, brightbox-cli.gemspec, lib/brightbox-cli/commands/login.rb, lib/brightbox-cli/config/sections.rb, spec/commands/login_spec.rb, spec/spec_helper.rb, spec/support/vcr.rb
A bug in the conditions meant the default URLs were being being replaced
each time `login` was used.
=> Don't reset custom URLs when reusing `login`

lib/brightbox-cli/config.rb, lib/brightbox-cli/config/authentication_tokens.rb, lib/brightbox-cli/config/sections.rb
`#client_alias` method was used by mistake instead of `config_alias`
variable.
This meant the config was set to the default account whilst clearing the
access token.
The `#renew_tokens` call used the correct client since it is passed in
as an argument. However the presence of the refresh token was the reason
`#renew_tokens` would hit the branch without using the password.
This would forced a password prompt and a confusing message.
=> Correctly set client name for `login`

lib/brightbox-cli/detailed_server.rb
Seems calling `attributes` a second time has a side effect which sets
`:zone` to be `nil`. We already have access to compatibility mode.
=> Fix blank zone in `brightbox servers show`

.travis.yml
Appears Travis CI updates to the environment shortly after the last set
of tests were run.
https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future
The new environment is causing a number of errors and failures.
This is switching to their container based build env to see if that
changes things.
=> Add `sudo: false` to Travis.yml

Gemfile.lock, brightbox-cli.gemspec
This primarily defaults the account nesting to be disabled resulting in
a faster version of `brightbox accounts list`
=> Update `fog-brightbox` to v0.10.1

lib/brightbox-cli/images.rb
As per https://github.com/brightbox/honcho/pull/712 we can now get
accounts without nesting all their resources, which speeds up the
request a lot for large accounts.
We use the account id when listing images to fiter by owner but we only
need the account id, so don't need nesting.
=> Don't nest account lookup when listing images

Gemfile.lock, brightbox-cli.gemspec, lib/brightbox-cli/database_server.rb, spec/commands/sql/instances/show_spec.rb, spec/unit/brightbox/database_server/maintenance_window_spec.rb
Whilst highly unlikely, this fixes a raised TypeError if the response
from the API does not have the `maintenance_weekday` field in the
response.
The most likely case of this is in specs where only a subset of the
response is needed for other testing concerns. This bug would require
those to have this field, just to avoid this bug.
=> Fix issue if `maintenance_weekday` not in JSON

lib/brightbox-cli/api.rb, lib/brightbox-cli/database_server.rb, spec/unit/brightbox/api/created_on_spec.rb, spec/unit/brightbox/database_server/cloud_ips_spec.rb
Changes to prevent errors when accessing fields where
the JSON/attributes have not been initialised.
Normally the API responses always include theses fields but
under tests, we can save boilerplate responses by making the
code more robust.
=> Guard more JSON fields

lib/brightbox-cli/commands/sql/instances_create.rb, lib/brightbox-cli/commands/sql/instances_update.rb, lib/brightbox-cli/database_server.rb, locales/en.yml, spec/commands/sql/instances/create_spec.rb, spec/commands/sql/instances/show_spec.rb, spec/commands/sql/instances/update_spec.rb
SQL instances can be configured to automatically perform a snapshot
based on a crontab schedule.
Fields are in the following order:
* Minutes (0-60) **Note** there is a limit of once per hour so the
minutes field may not be "*" or a range of values.
* Hours (0-23)
* Day of month (1-31)
* Month (1-12)
* Day of week (0-6) **Note** Sunday is 0
See https://en.wikipedia.org/wiki/Cron#Format
So the argument `--snapshots-schedule="0 5 * * 0"` will prepare a
schedule to run every Sunday at 05:00.
A schedule may be cleared with `--remove-snapshots-schedule`
=> Add support for `snapshots-schedule` argument

Gemfile.lock, brightbox-cli.gemspec, lib/brightbox-cli/commands/servers/create.rb, locales/en.yml, spec/commands/servers/create_spec.rb
This allows the creation of servers that immediately map a Cloud IP upon
being built.
The argument can accept either "true" which requests the allocation of a
new Cloud IP for the built.
Alternatively it can accept an identifier (`cli-12345`) for an unmapped
Cloud IP and that nominated IP will be reserved and mapped instead.
=> Add --cloud-ip argument to new server requests

.travis.yml
Ruby 1.9.3 seems to be having problems on Travis. Unfortunately, it
looks like changing the default bundler may resolve it.
=> Update bundler for Travis CI

Gemfile.lock, brightbox-cli.gemspec
The next release of `fog-brightbox` is planned to be a major release and
drops support for Ruby 1.9 and 2.0.
It also fixes a long standing namespacing issue that is incompatible
with the tests in this codebase.
So this updates `fog-brightbox` to fix a few issues and adds a
constraint so it will not pick up a v1.0 gem if updating itself.
=> Update and limit `fog-brightbox` dependency

lib/brightbox-cli/images.rb, spec/commands/images/list_spec.rb, spec/spec_helper.rb
When https://github.com/brightbox/brightbox-cli/pull/83 was merged, the
`account` was changed from a fog model (responding to `#id`) to a hash
with `#[]` key access.
At some point, the key type has changed - potentially caused by a Ruby
or `fog` change - from a symbol to a string.
The key change meant that the image listings had a filter that was used
by default but would filter anything without an owner ID of `nil`. That
meant everything.
The workaround was using `--show-all` which disabled this filter but
then included other images that were not interesting.
This fixes the key type to `String` for now which seems to work with
several versions of Ruby and the latest fog gems.
For: #97
=> Fix image filtering

lib/brightbox-cli/commands/token.rb, lib/brightbox-cli/token.rb, lib/brightbox_cli.rb
This adds a new command to display the currently available OAuth2 bearer
token cached by the tool.
$ brightbox token show
INFO: client_id: sample (sample)
access_token: 4f58a9eb8e91dbc9aba1fc8cc5dd21478f2ba03b
refresh_token: 34266b2428ca2d28d58ce0359c861fe2d0eef2e7
token_type: Bearer
It supports multiple output formats:
* 'text'  - Verbose table of tokens and values
* 'token' - Just the access token
* 'json'  - JSON version of 'text' for machine parsing.
* 'curl'  - Sample output for curl including header token and API URL.
=> Add `brightbox token` command

Gemfile.lock, brightbox-cli.gemspec
And issue in `fog-core` exposed an ordering bug where services were
being declared before autoloading was. The core change meant a large
deprecation warning and also an error.
Updating to `fog-brightbox v0.16.1` fixes the warning but it is safest
to limit fog-core to < 2.0 when deprecation behaviours were being added.
Due to upstream requirements, the dependency can not be declared in
fog-brightbox itself.
This also returns support for Ruby 1.9 which fog (core) drops in 2.0
=> Update `fog-brightbox` to v0.16.1

lib/brightbox-cli/token.rb
A typo left the curl formatted output invalid due to an extra space.
=> Fix errant space in `token` curl output

.travis.yml
Travis is supposed to be install a valid version of bundler for us now
and a version < 2 for Ruby versions older than 2.3
=> Do not manually install bundler

lib/brightbox-cli/commands/servers/activate-console.rb
The original URL construction assumed the original format and did not
dynamically assemble a valid URL from the API output.
This fixes it by using `URI` to assemble the parts without a trailing
slash that is incorrect.
=> Fix `servers` `activate_console` URL

Gemfile.lock, brightbox-cli.gemspec
`dry-inflector v2.0` dropped support for Rubies older than 2.4 and
enforced it in their gemspec. This causes issues on LTS versions of
Linux with older Ruby versions when installing the gem.
This limits it to older versions that are still supported so gem
installation should continue to work.
=> Fix `dry-inflector` to retain older Ruby support

.travis.yml, Gemfile.lock, Jenkinsfile, brightbox-cli.gemspec, lib/brightbox-cli/api.rb, lib/brightbox-cli/collaboration.rb, lib/brightbox-cli/commands/firewall/policies-update.rb, spec/support/shared/collaborating_accounts_context.rb, spec/unit/brightbox/account/all_spec.rb, spec/unit/brightbox/account/get_spec.rb, spec/unit/brightbox/api/conn_spec.rb, spec/unit/brightbox/collaborating_account_spec.rb, spec/unit/brightbox/connection_manager/fetch_connection_spec.rb, spec/unit/brightbox/database_server/cloud_ips_spec.rb, spec/unit/brightbox/database_server/maintenance_window_spec.rb, spec/unit/brightbox/user_collaboration/get_for_account_spec.rb, spec/unit/brightbox/user_collaboration/remove_spec.rb
This is an overdue major update to use `fog-brightbox v1.1.0`.
The update includes a backwards incompatible standardising of module
names from `Fog::Compute::Brightbox` to our own `Fog::Brightbox`
namespace pushed from `fog-core`
=> Update `fog-brightbox` to v1.1.0

Gemfile.lock, Rakefile, brightbox-cli.gemspec
Updating `rake` catches an issue where the earlier versions of RSpec
and its Rake task would reference `last_comment` which was removed from
Rake.
So to enable that RSpec needs updating.
=> Bump `rspec` from 2.99 to 3.9

spec/commands/sql/instances/create_spec.rb
The `sql instance create --snapshot` argument was broken due to a
missing attribute within `fog-brightbox`.
Updating to the `v1.1.0` release ensures that the command works as
expected since the API receives the correct parameters.
=> Confirm fix for creating SQL instance from snapshot

lib/brightbox-cli/cloud_ips.rb, spec/commands/cloudips/update_spec.rb
With an `empty?` guard in place we unintentionally prevented clearing
the name of a Cloud IP whilst preventing sending `nil`.
=> Fix `cloudips update` name with blank string

Gemfile.lock, brightbox-cli.gemspec, lib/brightbox-cli/commands/lbs/create.rb, lib/brightbox-cli/commands/lbs/show.rb, lib/brightbox-cli/commands/lbs/update.rb, lib/brightbox-cli/load_balancers.rb, spec/commands/lbs/create_spec.rb, spec/commands/lbs/update_spec.rb
The `ssl-min-ver` command can now set the minimum TLS/SSL version that
should be supported by the load balancer.
brightbox lbs create --ssl-min-ver TLSv1.0
TLSv1.0 is dated and whilst it has widest compatibily a number of
security vulnerability affect it. As does TLS1.1
TLSv1.2 is the default whilst TLSv1.3 is also supported.
=> Add `ssl-min-ver` argument to `lbs`

Gemfile.lock, brightbox-cli.gemspec, lib/brightbox-cli/commands/servers/create.rb, lib/brightbox-cli/detailed_server.rb, spec/commands/servers/create_spec.rb
This can be used to request encryption at rest for new server builds
where a LUKS volume is used to ensure the disk image is encrypted.
=> Add `servers --disk-encrypted` switch

.github/workflows/ruby.yml
Due to a mix up of documentation, it appears a wider range of Ruby
versions can be used for testing than first understood.
This adds testing back to Ruby 2.1.
=> Expand Ruby versions tested

CHANGELOG.md, brightbox-cli.gemspec
The message is very dated now and most users of the deployment gem will
be aware of the name change if they are using both gems.
=> Remove post install message

CHANGELOG.md, Gemfile.lock, brightbox-cli.gemspec
This should include some deprecation fixes for later versions of Ruby
that are starting to appear in the command line.
=> Update `gli` to v2.21.0

CHANGELOG.md, Gemfile.lock, brightbox-cli.gemspec
`dry-inflector` had to be pinned to a version < 0.2 as Ruby 2.3 support
was dropped in a minor release. Now that is no longer a constraint, we
can remove the pin and update the gem.
=> Update `dry-inflector` as Ruby limit removed

spec/support/vcr.rb
This has the unfortunate side-effect of creating conflicting entries in
VCR recordings where one run could get a 201 response, then another
request for `srv-12345` gets a 404 and the later entry took precidence.
All the identifiers used in testing are from a development instance so
are not leaking real identifiers.
When all the VCR tests correctly setup and tear down resources and can
re-record then the re-use of 12345 will just cause problems.
=> Remove VCR identifier sanitisation

.gitignore, spec/spec_helper.rb
Rather than running 600+ specs when a few fail, this configures RSpec to
keep track per example to streamline testing.
=> Configure RSpec to allow failed example re-runs

spec/spec_helper.rb
The default timeout for `fog` is 600 seconds so when an API call misses
a 10 minute wait is far too long. This cuts down to 10s which is just
enough to allow for replays and most requests.
=> Reduce testing timeout to 10 seconds

.gitattributes
A quality of life improvement to mark the VCR cassettes as generated on
GitHub to hopefully not overwhelm diffs with the changes when
re-recording.
=> Add `.gitattributes` to mark generated VCR files

Gemfile.lock, brightbox-cli.gemspec, spec/cassettes/Brightbox_Server/_destroy/when_server_exists/should_work.yml, spec/cassettes/Brightbox_Server/_show/when_server_exists/shows_detailed_attributes_of_a_server.yml, spec/cassettes/Brightbox_Server/_shutdown/should_work.yml, spec/cassettes/Brightbox_Server/_start/should_work.yml, spec/cassettes/Brightbox_Server/_stop/should_work.yml, spec/cassettes/brightbox_sql_instances/create/--allow-access_srv-12345_grp-12345/correctly_sends_API_parameters.yml, spec/cassettes/brightbox_sql_instances/create/--engine_mysql/correctly_sends_API_parameters.yml, spec/cassettes/brightbox_sql_instances/create/--engine_mysql_--engine-version_5_6/correctly_sends_API_parameters.yml, spec/cassettes/brightbox_sql_instances/create/--engine_mysql_--engine-version_8_0/correctly_sends_API_parameters.yml, spec/cassettes/brightbox_sql_instances/create/--maintenance-weekday_5_--maintenance_hour_11/correctly_sends_API_parameters.yml, spec/cassettes/brightbox_sql_instances/create/--maintenance-weekday_thursday/correctly_sends_API_parameters.yml, spec/cassettes/brightbox_sql_instances/create/--snapshot_dbi-12345/includes_schedule_fields_in_response.yml, spec/cassettes/brightbox_sql_instances/create/--snapshots-schedule_0_12_4_/includes_schedule_fields_in_response.yml, spec/cassettes/brightbox_sql_instances/create/without_arguments/reports_the_new_admin_password.yml, spec/cassettes/brightbox_sql_instances/create/without_arguments/reports_the_new_admin_username.yml, spec/commands/sql/instances/create_spec.rb
This update includes support for volume resources but have not been
added to the CLI yet.
This also updates a number of VCR recordings that failed to replay to
changes in the `fog-brightbox` implementation that resulted in missed
matches due to changes in the request format.
=> Update `fog-brightbox` to `v1.5.0`

.rubocop.yml, Gemfile.lock, brightbox-cli.gemspec
This was used but inconsistently applied without a centralised config.
This moves the current config into place as well as adding the gems to
the development list.
=> Setup `rubocop` for code quality

spec/commands/login_spec.rb, spec/spec_helper.rb, spec/support/authentication_helpers.rb, spec/support/password_prompt_helpers.rb
There is a configurable flag to enable the `login` command to support 2FA (offering a separate prompt) but it was not tested.
This adds helpers and replaces the VCR fixtures that do not allow us to mock the traffic we need to test this.
=> Add tests for 2FA login

Gemfile.lock, brightbox-cli.gemspec, lib/brightbox-cli/commands/login.rb, lib/brightbox-cli/config/authentication_tokens.rb, lib/brightbox-cli/config/password_helper.rb, lib/brightbox-cli/config/sections.rb, lib/brightbox-cli/config/two_factor_auth.rb, lib/brightbox-cli/config/two_factor_helper.rb, lib/brightbox-cli/config/user_application.rb, lib/brightbox-cli/connection_manager.rb, spec/commands/login_spec.rb, spec/unit/brightbox/config/discover_two_factor_pin_spec.rb
This enables the new option in `fog-brightbox v1.6.0` which will raise a
different error if a user's authentication fails due to them having Two
Factor Authentication (2FA) enabled but not supplying a One Time
Password (OTP).
This results in prompts for a user's OTP during certain actions such as
the `login` command or when tokens have expired and are being renewed.
This replaces the functionality enabled by the `two_factor` setting in
configurations. 2FA enrolment is automatically discovered or ignored.
=> Support Two Factor Authentication (2FA) properly

Gemfile.lock, brightbox-cli.gemspec
`dry-inflector v0.3` drops support for Ruby 2.5 and 2.6 which means
updating other resources can pull in an incompatible dependency for the
older versions we support.
This pins to the 0.2 series.
=> Pin `dry-inflector` to support Ruby 2.5

Gemfile.lock, brightbox-cli.gemspec
This adds support for `ConfigMap` resources and updates to include the
attributes currently available in the API.
=> Update `fog-brightbox` to `v1.7.0`

lib/brightbox-cli/commands/images/register.rb, lib/brightbox-cli/commands/images/show.rb, lib/brightbox-cli/commands/images/update.rb, lib/brightbox-cli/images.rb, spec/commands/images/register_spec.rb, spec/commands/images/show_spec.rb, spec/commands/images/update_spec.rb, spec/support/authentication_helpers.rb
This allows passing an `min-ram` argument that can be used to mark an
image as requiring a minimum amount of RAM so creating a server from too
small a type will report an error.
Rather than an instance building and failing at some point as it runs
out of memory at some point.
=> Add `min-ram` argument to Images

Jenkinsfile
Our internal CI setup had unsupported versions of Ruby running
and some of the cached images had too old version of `bundle`.
These changes fix that and bring it in line with GitHub actions.
=> Update jenkinsfile to fix changes made by v4.0

Gemfile.lock, brightbox-cli.gemspec
Under Ruby 2.7, deprecation warnings could appear due to `mime-types`
using numbered parameters (`_1`) internally and them now becoming
reserved.
This relaxes the dependency to pick up a later, fixed version to avoid
cluttering the output.
=> Bump `mime-types` to v3.4.1

lib/brightbox-cli/commands/servers/create.rb, spec/commands/servers/create_spec.rb
The API does not accept empty arrays of groups as each server must be
assigned to a group. A server side workaround has been in place to
account for this long standing bug where the unset `server-groups` flag
would report an empty array.
The workaround strips out empty lists and uses the default group which
is the expected behaviour. The newer API documentation had to be
reported incorrectly to account for the workaround.
=> Fix empty server groups during `servers create`

Gemfile.lock, brightbox-cli.gemspec, lib/brightbox-cli/commands/servers/create.rb, locales/en.yml, spec/commands/servers/create_spec.rb
This allows passing of an arbitary size for the network block storage
volume when using a "nbs" server type.
=> Add `volume-size` flag to `servers create`

Gemfile.lock, brightbox-cli.gemspec, lib/brightbox-cli/commands/volumes/attach.rb, lib/brightbox-cli/commands/volumes/copy.rb, lib/brightbox-cli/commands/volumes/create.rb, lib/brightbox-cli/commands/volumes/destroy.rb, lib/brightbox-cli/commands/volumes/detach.rb, lib/brightbox-cli/commands/volumes/list.rb, lib/brightbox-cli/commands/volumes/locking.rb, lib/brightbox-cli/commands/volumes/resize.rb, lib/brightbox-cli/commands/volumes/show.rb, lib/brightbox-cli/commands/volumes/update.rb, lib/brightbox-cli/detailed_server.rb, lib/brightbox-cli/volume.rb, lib/brightbox_cli.rb, locales/en.yml, spec/commands/volumes/attach_spec.rb, spec/commands/volumes/copy_spec.rb, spec/commands/volumes/create_spec.rb, spec/commands/volumes/destroy_spec.rb, spec/commands/volumes/detach_spec.rb, spec/commands/volumes/list_spec.rb, spec/commands/volumes/resize_spec.rb, spec/commands/volumes/show_spec.rb, spec/commands/volumes/update_spec.rb, spec/support/volume_helpers.rb
This adds support for `Volume` management with the subcommands:
* `create` - create a new detached network volume
* `list` - returns a summary of all volumes on an account
* `show` - returns details of a given account
* `update` - updates volume attributes
* `destroy` - deletes a detached network volume
* `attach` - attaches volume to a server
* `detach` - detaches a volume from a server
* `resize` - increases the size of a volume
* `copy` - duplicates an existing volume
=> Add `Volume` management commands

locales/en.yml
Missing quotes resulted in GLI crashing parsing an Array prepared by YAML rather than just handling a String which it supports.
=> Fix `help` output crashing by encountering Array

lib/brightbox-cli/commands/lbs/update.rb, lib/brightbox-cli/commands/servers/create.rb, lib/brightbox-cli/commands/servers/update.rb, lib/brightbox-cli/commands/volumes/update.rb, lib/brightbox_cli.rb, lib/gli_patches.rb, spec/commands/cloudips/update_spec.rb, spec/commands/lbs/update_spec.rb, spec/commands/servers/create_spec.rb, spec/commands/servers/update_spec.rb, spec/commands/sql/instances/update_spec.rb, spec/commands/volumes/update_spec.rb
The GLI frameworks assumes that if a switch is defined, it should always be present with a `true` or `false`. This prevents using switches to represent boolean API settings since defining one injects it into the parsed arguments.
This can not be detected within CLI actions, we can not tell if the user passed `--feature`, `--no-feature`, or did not include the flag at all. This may result in a `update --name New` call also setting the feature to a default of false.
The default can be abused with a non-boolean value and used to remove it from the parameters passed to the API but being `truthy` results in the CLI help being incorrect. It lists a default when there isn't one.
This monkey patches GLI to support a `ignore_default` option which can be set to `true` and it is skipped when …
=> Fix intrusive CLI switch defaults

Gemfile.lock, brightbox-cli.gemspec, lib/brightbox-cli/commands/sql/instances_reset.rb, lib/brightbox-cli/commands/sql/instances_resize.rb, lib/brightbox-cli/database_server.rb, locales/en.yml, spec/commands/sql/instances/reset_spec.rb, spec/commands/sql/instances/resize_spec.rb
New API methods to support resizing of database servers and resetting of the DBMS are now covered by the following two commands:
brightbox sql instances resize --type dbt-abcde dbs-12345
brightbox sql instances reset dbs-12345
=> Add DBS `reset` and `resize` subcommands

lib/brightbox-cli/commands/images/register.rb, spec/commands/images/register_spec.rb
The `source` option was tied to the FTP based workflow which is no longer supported. Thus the option would trigger an unresolvable error for the CLI user.
Using the `url` option against a publicly accessible image via HTTP(S), such as a temp URL in Orbit is the preferred approach to register.
=> Remove `source` option from `images register`

.github/workflows/ruby.yml
By summer github actions will no longer support node 12 (used by checkout@v2) RM27728
=> Update from node 12 to 16 (node 12 will EOL soon)

.github/workflows/ruby.yml, Gemfile.lock, brightbox-cli.gemspec, lib/brightbox-cli/version.rb
The version of bundler is inconsistent over versions with older Rubies attempting to use versions they do not support. This attempts to tie them together.
=> Update workflow to install nominated bundler

lib/brightbox-cli/load_balancers.rb
The parsed key has switched from Symbol to String and so the guard clause in part of the `lbs` command no longer reports mapped IPs.
=> Fix parsing of load balancer cloud IP details

lib/brightbox-cli/commands/firewall/policies_apply.rb, lib/brightbox-cli/commands/firewall/policies_create.rb, lib/brightbox-cli/commands/firewall/policies_destroy.rb, lib/brightbox-cli/commands/firewall/policies_list.rb, lib/brightbox-cli/commands/firewall/policies_remove.rb, lib/brightbox-cli/commands/firewall/policies_show.rb, lib/brightbox-cli/commands/firewall/policies_update.rb
A requested option was to support the singular version of "policies" since auto-completion does not work with "policy" like it can do with other resources just missing the "s".
=> Allow singular `firewall-policy` command version

lib/brightbox-cli/config.rb, spec/unit/brightbox/bb_config/config_directory_spec.rb
In some container environments, `$HOME` may not be set as an ENV variable resulting in the configuration either returning `/.brightbox` or in later versions raising an error as the file path would error when joining `nil`.
For: GH-96
=> Fall back to working DIR if `$HOME` unset

Gemfile.lock
To remove an issue with a spelling warning spamming on every run but limiting it to a version supported by Ruby 2.7.
=> Update `bundler` to v2.4.22

Gemfile.lock, brightbox-cli.gemspec
This fixes a few issues related to very old or newest versions of Ruby and fallout from upstream dependency changes.
=> Update `fog-brightbox` for v1.12.0

lib/brightbox-cli/commands/lbs/create.rb, lib/brightbox-cli/commands/lbs/show.rb, lib/brightbox-cli/commands/lbs/update.rb, lib/brightbox-cli/load_balancers.rb, spec/commands/lbs/create_spec.rb, spec/commands/lbs/show_spec.rb, spec/commands/lbs/update_spec.rb
Passing a list of comma separated domains to either `lbs create` or `lbs
update` will request that domains are provisioned from Let's Encrypt.
For this to work a `https` (not `tcp`) listener needs to be available on
port 443 otherwise the request will be rejected.
brightbox lbs create --acme-domains domain.example --listeners 443:443:https:5000 srv-12345
Domains and their status are listed under the `lbs show` command output.
=> Add ACME support for `lba` commands

lib/brightbox-cli/commands/lbs/create.rb, spec/commands/lbs/create_spec.rb
The API previously enforced a minimum of one server to be balanced and that was encoded in the CLI. The technical requirement for that has long since gone and the API no longer enforces it.
This removes it so load balancers without nodes can now be created.
=> Remove requirement for one load balancer node

.github/workflows/ruby.yml
To prevent regressions when examples assume STDERR is empty but passing `DEBUG` will output addition text and fail it, this sets it in the CI environments to catch it during testing and not months later under manual testing.
=> Pass `DEBUG=true` to CI specs

spec/spec_helper.rb
A number of underlying superclasses were not discovered by the autoloading setup in use resulting in missing entries and a drop in overall coverage to 76%.
This changes the the setup to ensure things like `api.rb` are covered.
=> Coverage was not tracking a number of files

lib/brightbox-cli/commands/lbs/show.rb, lib/brightbox-cli/load_balancers.rb, spec/commands/lbs/show_spec.rb, spec/unit/brightbox/load_balancer/acme_cert_spec.rb, spec/unit/brightbox/load_balancer/formatted_acme_domains_spec.rb
This displays ACME certificate details for load balancers show output.
=> Add extended ACME support

lib/brightbox-cli/images.rb
Originally the image architecture was embedded into the name for display but that caused issues with parsing, especially if parentheses we used in the name.
It also resulted in duplication in the `images show` command as the `arch` field was also included but the name without was not.
This splits them apart rather than combining them.
=> Move Image `arch` to own column/remove from name
